import { FastifyInstance } from 'fastify';
import { authenticate } from '../middleware/auth';
import { PaymentController } from '../controllers/payment.controller';

export const paymentRoutes = async (app: FastifyInstance) => {
  // Routes requiring auth
  app.register(async (authApp) => {
    authApp.addHook('preValidation', authenticate);
    
    // Explicit manual verification generated by frontend Razorpay Checkout
    authApp.post('/payments/verify', PaymentController.verifyPayment);
  });
};
